rm(list = ls()) # Remove all the objects we created so far.

#Load in external graph files
survey_edges <- data.frame(read.csv("../not_shared/output/edges.csv", header = TRUE, stringsAsFactors = FALSE))
survey_nodes <- data.frame(read.csv("../not_shared/output/nodes.csv", header = TRUE, stringsAsFactors = FALSE))

#Create an igraph objects
network_all <- graph_from_data_frame(d=survey_edges, vertices = survey_nodes, directed = T)
network_basic_needs <- induced.subgraph(network_all, which(V(network_all)$Filter.Sector.Basic_needs==TRUE))
network_education <- induced.subgraph(network_all, which(V(network_all)$Filter.Sector.Education==TRUE))
network_food_security <- induced.subgraph(network_all, which(V(network_all)$Filter.Sector.Food_security==TRUE))
network_health <- induced.subgraph(network_all, which(V(network_all)$Filter.Sector.Health==TRUE))
network_livelihoods <- induced.subgraph(network_all, which(V(network_all)$Filter.Sector.Livelihoods==TRUE))
network_protection <- induced.subgraph(network_all, which(V(network_all)$Filter.Sector.Protection==TRUE))
network_shelter <- induced.subgraph(network_all, which(V(network_all)$Filter.Sector.Shelter==TRUE))
network_wash <- induced.subgraph(network_all, which(V(network_all)$Filter.Sector.WASH==TRUE))

sector_stats <- data.frame(
  name=c("All", "Basic_needs", "Education", "Food_security", "Health", "Livelihoods", "Protection", "Shelter", "WASH"),
  count_nodes=c(vcount(network_all),
                vcount(network_basic_needs),
                vcount(network_education),
                vcount(network_food_security),
                vcount(network_health),
                vcount(network_livelihoods),
                vcount(network_protection),
                vcount(network_shelter),
                vcount(network_wash)),
  count_edges=c(ecount(network_all),
                ecount(network_basic_needs),
                ecount(network_education),
                ecount(network_food_security),
                ecount(network_health),
                ecount(network_livelihoods),
                ecount(network_protection),
                ecount(network_shelter),
                ecount(network_wash)),
  density=c(graph.density(network_all,loops = FALSE),
                graph.density(network_basic_needs,loops = FALSE),
                graph.density(network_education,loops = FALSE),
                graph.density(network_food_security,loops = FALSE),
                graph.density(network_health,loops = FALSE),
                graph.density(network_livelihoods,loops = FALSE),
                graph.density(network_protection,loops = FALSE),
                graph.density(network_shelter,loops = FALSE),
                graph.density(network_wash,loops = FALSE)),
  centrality_out=c(mean(degree(network_all,mode="out")),
            mean(degree(network_basic_needs,mode="out")),
            mean(degree(network_education,mode="out")),
            mean(degree(network_food_security,mode="out")),
            mean(degree(network_health,mode="out")),
            mean(degree(network_livelihoods,mode="out")),
            mean(degree(network_protection,mode="out")),
            mean(degree(network_shelter,mode="out")),
            mean(degree(network_wash,mode="out"))),
  centrality_in=c(mean(degree(network_all,mode="in")),
                   mean(degree(network_basic_needs,mode="in")),
                   mean(degree(network_education,mode="in")),
                   mean(degree(network_food_security,mode="in")),
                   mean(degree(network_health,mode="in")),
                   mean(degree(network_livelihoods,mode="in")),
                   mean(degree(network_protection,mode="in")),
                   mean(degree(network_shelter,mode="in")),
                   mean(degree(network_wash,mode="in"))),
  centrality_all=c(mean(degree(network_all,mode="all")),
                   mean(degree(network_basic_needs,mode="all")),
                   mean(degree(network_education,mode="all")),
                   mean(degree(network_food_security,mode="all")),
                   mean(degree(network_health,mode="all")),
                   mean(degree(network_livelihoods,mode="all")),
                   mean(degree(network_protection,mode="all")),
                   mean(degree(network_shelter,mode="all")),
                   mean(degree(network_wash,mode="all"))),
  shortest_path=NA,
  avg_path_length=NA,
  diameter=c(diameter(network_all,directed=TRUE),
                   diameter(network_basic_needs,directed=TRUE),
                   diameter(network_education,directed=TRUE),
                   diameter(network_food_security,directed=TRUE),
                   diameter(network_health,directed=TRUE),
                   diameter(network_livelihoods,directed=TRUE),
                   diameter(network_protection,directed=TRUE),
                   diameter(network_shelter,directed=TRUE),
                   diameter(network_wash,directed=TRUE)),
  DPOM=c(mean(V(network_all)$Format.Data_protection.Organisational_measures),
         mean(V(network_basic_needs)$Format.Data_protection.Organisational_measures),
         mean(V(network_education)$Format.Data_protection.Organisational_measures),
         mean(V(network_food_security)$Format.Data_protection.Organisational_measures),
         mean(V(network_health)$Format.Data_protection.Organisational_measures),
         mean(V(network_livelihoods)$Format.Data_protection.Organisational_measures),
         mean(V(network_protection)$Format.Data_protection.Organisational_measures),
         mean(V(network_shelter)$Format.Data_protection.Organisational_measures),
         mean(V(network_wash)$Format.Data_protection.Organisational_measures)),
  DPPM=c(mean(V(network_all)$Format.Data_protection.Physical_measures),
         mean(V(network_basic_needs)$Format.Data_protection.Physical_measures),
         mean(V(network_education)$Format.Data_protection.Physical_measures),
         mean(V(network_food_security)$Format.Data_protection.Physical_measures),
         mean(V(network_health)$Format.Data_protection.Physical_measures),
         mean(V(network_livelihoods)$Format.Data_protection.Physical_measures),
         mean(V(network_protection)$Format.Data_protection.Physical_measures),
         mean(V(network_shelter)$Format.Data_protection.Physical_measures),
         mean(V(network_wash)$Format.Data_protection.Physical_measures)),
  DPTM=c(mean(V(network_all)$Format.Data_protection.Technical_measures),
         mean(V(network_basic_needs)$Format.Data_protection.Technical_measures),
         mean(V(network_education)$Format.Data_protection.Technical_measures),
         mean(V(network_food_security)$Format.Data_protection.Technical_measures),
         mean(V(network_health)$Format.Data_protection.Technical_measures),
         mean(V(network_livelihoods)$Format.Data_protection.Technical_measures),
         mean(V(network_protection)$Format.Data_protection.Technical_measures),
         mean(V(network_shelter)$Format.Data_protection.Technical_measures),
         mean(V(network_wash)$Format.Data_protection.Technical_measures)),
  DPRDS=c(mean(V(network_all)$Format.Data_protection.Rights_of_data_subject_measures),
         mean(V(network_basic_needs)$Format.Data_protection.Rights_of_data_subject_measures),
         mean(V(network_education)$Format.Data_protection.Rights_of_data_subject_measures),
         mean(V(network_food_security)$Format.Data_protection.Rights_of_data_subject_measures),
         mean(V(network_health)$Format.Data_protection.Rights_of_data_subject_measures),
         mean(V(network_livelihoods)$Format.Data_protection.Rights_of_data_subject_measures),
         mean(V(network_protection)$Format.Data_protection.Rights_of_data_subject_measures),
         mean(V(network_shelter)$Format.Data_protection.Rights_of_data_subject_measures),
         mean(V(network_wash)$Format.Data_protection.Rights_of_data_subject_measures)),
  DPODS=NA,
  DP=NA
)